### ISSUE TITLE
Multiple files utility

### ISSUE THREAD

**Issue by harshithmohan** [ShokoAnime/Shoko-WebUI#470]
![image](https://user-images.githubusercontent.com/26010946/205226591-befa13d3-133d-4961-90d6-517e7f3fa387.png)
![image](https://user-images.githubusercontent.com/26010946/205226610-a0b9a5fb-7708-46b4-a2f2-ac2dbe1608f6.png)

**Comment by ElementalCrisis** [comment]
https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/cc61b5d7-a54d-4df9-844b-fd4e3c4c8c13

Video showing latest mockups.

**Comment by ElementalCrisis** [comment]
@harshithmohan are we good to close this?
