### ISSUE TITLE
Collection - List View

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/Shoko-WebUI#475]
Here's what we're currently missing.

- ~~Ongoing Series indicator.~~
- ~~Group Breakdown (4 Series | 3 Movies | 2 OVAs)~~
- Jump Bar

UI changes to make.

- Only user tags are green, normal tags are blue.
- ~~Increase overall padding on tags.~~
- ~~Series description does not need to be bold.~~
- ~~Parse out AniDB links in description.~~ 
- ~~Add visible divider between series.~~

![image](https://user-images.githubusercontent.com/9443295/205233668-7831ef81-ba02-431d-96f5-76e68185d5f4.png)

**Comment by hidden4003** [comment]
Regarding the tags I didn't see any distinction between the tags (i.e. user or otherwise), I only get Name, Description and Weight. @revam since you did the API, can we get the user/normal tag in there ?

**Comment by harshithmohan** [comment]
@hidden4003 Source key in the tag model
![image](https://user-images.githubusercontent.com/26010946/205281742-6666c303-2b3d-4d09-a8bb-10ced1d00892.png)

**Comment by revam** [comment]
I'll add it before i forget.

**Comment by hidden4003** [comment]
@ElementalCrisis looks like you fixed some of this in the #488 PR

**Comment by ElementalCrisis** [comment]
@revam status on user tags?

**Comment by revam** [comment]
> @revam status on user tags?

They're there (if your have any)

**Comment by revam** [comment]
No endpoints to create them yet though

**Comment by ElementalCrisis** [comment]
New design for reference.

![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/b9cee7b9-a146-4804-aeae-50d6e0f17799)

Still need user tags.

**Comment by revam** [comment]
They will still be there (if you have any)
