### ISSUE TITLE
Series/Group Quick Edit

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/Shoko-WebUI#487]
https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/2d015f23-f486-419d-9f02-4384911666d4

Modal height should be static, changing size in video due to a limitation of Figma.

**Comment by revam** [comment]
Is it safe to assume that only one of the "series name" or "group name" sections should be present depending on if we're editing a series or group?

**Comment by ElementalCrisis** [comment]
If editing a group then it's just the group name you can change, we can hide the series name input. However, when editing a series, the user can change the group if they'd like. For example, if they use custom grouping.
