### ISSUE TITLE
Add new error boundary and put an update button on the page

### ISSUE THREAD

**Issue by harshithmohan** [ShokoAnime/Shoko-WebUI#569]
This error boundary is from webui v1. We need to add a similar one for webui v2 because if an error occurs it just shows "No Route Found" instead of any details. There should be something no matter how useless it is.

We should also add a webui update button to that page so that it's easier for users to apply updates whenever they are on a version which is broken.

![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/26010946/ea997cb9-327e-4d23-86c0-1f66305f1bf2)

**Comment by ElementalCrisis** [comment]
Completed in https://github.com/ShokoAnime/Shoko-WebUI/commit/bab4aff6053121e9ed942dfc1b6e5dc1a9a0e70e
