### ISSUE TITLE
TypeError: exclusions.split is not a function

### ISSUE THREAD

**Issue by sheharyarn** [ShokoAnime/Shoko-WebUI#586]
## Environment Details

- Server Version: v4.2.2
- WebUI Version: v1.1.1
- Docker Image: v4.2.2 [`shokoanime/server:latest`](https://hub.docker.com/layers/shokoanime/server/latest/images/sha256-c26109ccae2a8ce3ce05ebdfcf35e571ea4e43a3a38f22aa22eebd417263b8e2?context=explore)
- Docker 20.10.21 (baeda1f)
- Unraid 6.11.5

## To Reproduce

1. Login to Shoko Server
2. Click on "Settings" in the left sidebar
3. The error below shows up

## Error Details

```
ERROR

You broke the Web UI, congratulations.

Hopefully useful information:

TypeError: exclusions.split is not a function

Trace:


    in RelationSettings
    in Connect(RelationSettings)
    in div
    in Resizable
    in DraggableCore
    in GridItem
    in div
    in ReactGridLayout
    in ResponsiveReactGridLayout
    in WidthProvider
    in SettingsTab
    in Connect(SettingsTab)
    in div
    in div
    in div
    in MainPage
    in Connect(MainPage)
    in Route
    in AuthenticatedRoute
    in Connect(AuthenticatedRoute)
    in Switch
    in Router
    in ConnectedRouter
    in ConnectedRouterWithContext
    in Connect(ConnectedRouterWithContext)
    in div
    in Unknown
    in Connect(Component)
    in ErrorBoundary
    in ErrorBoundary
    in components_Provider
    in app

Go back, or head over to the home page to choose a new direction.
```

**Comment by revam** [comment]
Don't use the beta web ui with a stable server.

**Comment by sheharyarn** [comment]
I am not selecting the UI version manually. I am just pulling the latest docker and using that

**Comment by revam** [comment]
Did you update from 4.1.2 9 or earlier,  or is this a new install?

**Comment by sheharyarn** [comment]
> Did you update from 4.1.2 9 or earlier, or is this a new install?

This was an update, not a new install. I hadn't logged in Shoko for quite a while, and just updated to the latest docker image (4.2.2).

> Can you provide the web ui version used?

Web UI version 1.1.1.

**Comment by revam** [comment]
Try updating to 1.1.11, either manually, or theough swagger (since you can't in the web ui itself it seems)

**Comment by revam** [comment]
...do you need instructions for how to do that? (The conversation suddenly went silent)

**Comment by sheharyarn** [comment]
Yes, instructions would be great. Is there a specific docker image I should pull? Please note that I'm using this on Unraid so docker is the only option available to me.

**Comment by ElementalCrisis** [comment]
Stale, closing.

**Comment by revam** [comment]
I f9rgot to send the instructions 😅
