### ISSUE TITLE
Series - Episode Viewing Bugs

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/Shoko-WebUI#590]
- Clicking "File Info" pushes the episode up instead of pushing the episode below down. 

- Using "Search & Filter" causes the browser to jump when the new filter is applied. 
https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/7b7fb813-b22c-4fc6-9520-63c97e167fa7

- Opening an entry and changing filter causes the first entry in the new filter to render as expanded. 
https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/2e5092e7-e848-4789-888e-bb3dbae30956

**Comment by ElementalCrisis** [comment]
1. Has been fixed.
2. Not really an issue anymore.
3. State related issue, still needs to be resolved.

**Comment by hidden4003** [comment]
3. Should be fixed, reopen if it isn't
