### ISSUE TITLE
Recommended/Similar Anime Scrollbar Spacing 

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/Shoko-WebUI#608]
Scrollbar is too close to the content, should mirror the dashboard. 

![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/e0eb4871-21da-488c-a0a4-f4c97c22a747)

![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/9443295/3575382b-0cfb-468a-be97-1adbe7d5c943)

**Comment by harshithmohan** [comment]
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/26010946/12e6aea7-4843-4cb6-ae7e-9e068f36d7ae)

uhh.. this happens if we add padding and scrollbar is not visible. Is this fine?

**Comment by harshithmohan** [comment]
Dashboard is a different case since that's in grid layout and uses a non-auto height

**Comment by ElementalCrisis** [comment]
We didn't have this problem before, wonder what changed to cause it. 

I don't think we should always show the scrollbar, that just seems like a bad design style. The additional padding looks bad as well since it will be super noticeable. 

I had something working prior but overwrote my changes, let me see if I can get it working again.

**Comment by harshithmohan** [comment]
Only other solution I can think of is to set the panel to a fixed height
