### ISSUE TITLE
Populating Average Length

### ISSUE THREAD

**Issue by ElementalCrisis** [ShokoAnime/Shoko-WebUI#668]
This doesn't need to be complicated so what I think we should do is if a series has more than 1 episode, grab the runtime from episode two since a lot of series have an extended first episode and just use that. Of course, if there's only one episode, then use that runtime.

**Comment by harshithmohan** [comment]
Server will return the runtime?
WebUI doesn't load the episodes till we open the episodes tab.

**Comment by revam** [comment]
In the web ui series data. @harshithmohan remind me to add it later, please.

**Comment by ElementalCrisis** [comment]
This has been added.
