### ISSUE TITLE
Wrong episode prefixes

### ISSUE THREAD

**Issue by harshithmohan** [ShokoAnime/Shoko-WebUI#696]
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/26010946/60c66ab7-104d-4e0f-8d07-b53645186b42)

Currently, we are taking the first character of the `Type` of the episode. In this case, it is 'T' because the type is `ThemeSong`. Ideally, this be 'C' to match AniDB's prefix.

Need to map episode types to prefixes to match AniDB and use those instead

**Comment by revam** [comment]
We can also take it one step further and parse if it is OP1, ED1, etc. So it matches what anidb displays on their site.

**Comment by harshithmohan** [comment]
Fixed in #701
