### ISSUE TITLE
Filters missing (cut) from "Filters" Modal in Collection

### ISSUE THREAD

**Issue by krbrs** [ShokoAnime/Shoko-WebUI#761]
Filters are missing from the "Filters" modal in Collection view.

Shoko Desktop:

<img width="376" alt="filters_desktop" src="https://github.com/ShokoAnime/Shoko-WebUI/assets/57227244/9c3c1028-0845-4eea-819e-23a74760807d">

Shoko WebUI:

<img width="712" alt="filters_webui" src="https://github.com/ShokoAnime/Shoko-WebUI/assets/57227244/63ca26c6-d9e2-460a-be81-ac541207399e">

It looks like this happens because the Filter API endpoint is paginated and no pageSize parameter is passed.

Tested on Swagger - if "pageSize" is not set on the "api/v3/Filter?" query, it will default to "10", which results in the same as what WebUI displays because the filters list is being cut.

Adding pageSize: 0 to line 14 on filter/queries.ts might overflow the modal because there are too many filters, like this:

<img width="721" alt="filters_pagesize" src="https://github.com/ShokoAnime/Shoko-WebUI/assets/57227244/077100da-2baf-4611-b6d9-14497aba30b2">

Best would be to make the Filters list scrollable - I don't know how to do that tho

**Comment by ElementalCrisis** [comment]
I think we can set it to 0 so it loads all as majority of people probably have less than 20 filters. 

Thoughts @harshithmohan and @hidden4003?

**Comment by krbrs** [comment]
Looks like https://github.com/ShokoAnime/Shoko-WebUI/commit/6490f66c6cc17d235639e939eaa589f95c177049 fixes the overflow. Tested with pageSize: 0 param:

<img width="716" alt="filters_new" src="https://github.com/ShokoAnime/Shoko-WebUI/assets/57227244/b9f99862-3268-441a-913a-8e630609fb93">

**Comment by harshithmohan** [comment]
> I think we can set it to 0 so it loads all as majority of people probably have less than 20 filters.
> 
> Thoughts @harshithmohan and @hidden4003?

yeah, shouldn't be a problem.
@krbrs Make a PR 👍

**Comment by harshithmohan** [comment]
Fixed in #766
