### ISSUE TITLE
First Run Notification

### ISSUE THREAD

**Issue by duehoa1211** [ShokoAnime/Shoko-WebUI#830]
![image](https://github.com/ShokoAnime/Shoko-WebUI/assets/11846133/5252e058-9d90-4998-b79b-813b497a7682)

@ElementalCrisis asked me to implement this one.
With following requirements:

- Tie it to First Run
- First is changed when Set Me Free clicked
- User cannot do anything untile they click the button

**Comment by harshithmohan** [comment]
Completed in #831
