### ISSUE TITLE
[feature request] option to set display order in collections (the Monogatari problem)

### ISSUE THREAD

**Issue by tamodolo** [ShokoAnime/Shoko-WebUI#946]
It seems the way Shoko order shows is by release date (timeline). The Monogatari series is a perfect example to get things right on Shoko because it's a nightmare how metadata is arranged by the many metadata providers for this show thanks to crazy release decisions. And there's the Season 0 that agregates all specials and what to do with it. Probably will solve problems for other series too like Black Butler. I have little skills with programing language used for Shoko WebUI and Shoko Server so I'll leave here an initial logic based only on AniDB relations to propose a solution for this. I'll also propose 2 ways to arrange episode order in a collection.

The main objective of this is to provide a solution for watch order based on user's preference. Both solutions involves aboling Season 0 to achieve sane special ordering. For those who like have Season 0 then the actual standard is ok but some of the second proposition should be ofered as option.

Please, before ruling out this consider that none of the existing listing methods need to desapear. This is to add options. Mainly for those who just want to make a watchlist ordering more sane. This has nothing to do with intended author listing. It's just a method to create continuity in the show watchlist.

1. Release order but with proper special ordering.

This obeys the ordering used now but with changes specials as they will be listed inside the actual Season it belongs.

Rules proposition:

- list specials inside actual season conforming to what anidb informs as a base. If another metadata provider also have this info maybe this should be expressed as option for the end user.
- order specials by air date (this may solve 90% of watchlist ordering. Unfortunately nothing can be done with the Steins Gate beta episode... Except if exceptions may be created...). There's a tag to indicate that the episode is a recap. This may be used to limit episodes that is alowed to be listed in the middle of a season. Other specials are harder to be identified like episode 0 or new episodes that wasn't aired (like the 3 extra episodes of Bakemonogatari). Based on this the Air Date should be enough to decide if specials that are not recaps should be added before or after the season's normal episodes.
- I didn't found other entries to help with that but other metadata providers may have. I think this could be looked at to help but not as first solution.

Ordering the mess above:

- No Season 0
- Recaps order by air date inside actual season
- other specials ordered by air date before or after season episodes. Decision by special.

2. Season order by Show's Chonological order.

This obey the relations ordering present on anidb. I find this ordering amazing and no other metadata provider have anything close to this. Let's use this better.

Let's discuss this. This was born by my own frustration trying to properly catalog in a good way to watch animes.

Rules proposition:

- Direct relations must be respected as priority with indirect relations as secundary.
- Indirect relations needs a filter selection to what relation will be considered for collections. A "side show" may be considered but not "same setting" as example. Direct relations for indirect relations may be ignored in this context. Example: a side story got a sequel. Both shows should be considered as side stories for the main show. This should resolve the problem of where it should be. Probably need a main show reference to work properly.
- Shows with more then one direct sequel will use air date to decide what will be listed first. This should solve the Black Butler sequel problem. 
- Rules for specials above should be included here

Ordering the mess above:

- Direct Relations will be respected (prequel/sequel regardless of type of show)
- Indirect relations will be between direct relations (side story.
- indirect relations will be listed after it's referense.
- if indirect relation of many direct relations exist then it'll be listed after the most advanced one in direct relations.
- if indirect relations have direct relation then the former should have secundary priority over it's own indirect relation to main series.
- if a show have two direct relation then it should be listed in air date order. Both sequel and prequel.
- if a show continues with it's side story instead of main show then priority should shift to it using air date as reference. This is the case of a show that don't have indirect relation but is direct related to a side story. (Monogatari case again)
- Cases like Steins;Gate may need manual tweak. Maybe an edit tool to let users to change this could be done afterwards.

I know this is not perfect and flaws may occur but I think this is a beginning for creating better watchlists.

**Comment by revam** [comment]
- "Seasons" are not a thing in Shoko. So there is no "season 0"
- We don't have access to episode or character tags as they're not included in the AniDB HTTP or UDP APIs.
- Chronological ordering of **Series** inside **Groups** can get muddy real fast.

Good luck to whomever which may try implementing this logic.

**Comment by harshithmohan** [comment]
- Season 0 of what? Are you talking about plex or jellyifn or kodi? Shoko doesn't have seasons. They are groups and group of series.
- The particular metadata agent of the media player has to handle the order since Shoko doesn't do any ordering.

**Comment by ElementalCrisis** [comment]
Sorry, we're not going to add the required logic for this. 

The timeline panel in a group view is not meant to be a source of truth/recommended viewing order for the series in a groups. Groups themselves are more of a container and can contain un-related series if the user desires it. When I designed  the timeline panel, we had these discussions and ultimately decided it was better to keep it simple and just show the series sorted by release.
