### ISSUE TITLE
After fresh install and opt-out of analitics I get Error in WebUI

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/Shoko-WebUI#960]
![obraz](https://github.com/user-attachments/assets/63c05012-8622-4c15-97c5-818d8d03940b)

Is this function working or is this just visual error on WebUI side ?

edit: this pop up also shows when I changes tabs in webui.

**Comment by harshithmohan** [comment]
GA doesn't exist anymore and that is the old webui

**Comment by bigretromike** [comment]
> GA doesn't exist anymore and that is the old webui

This is what came with stable 4.2.2, just saying

**Comment by ElementalCrisis** [comment]
It's fine, old stable Web UI will be replaced soon and as @harshithmohan mentioned, we don't even use Google Analytics anymore.
