### ISSUE TITLE
"Relation" is only component that use scrollbar which is not indicated in any way before you start scrolling/hover on it

### ISSUE THREAD

**Issue by bigretromike** [ShokoAnime/Shoko-WebUI#963]
![obraz](https://github.com/user-attachments/assets/c2dd5805-d9b6-4bea-a03e-b066d77e8c2a)

Is this by design ? On touch screen its a bit misleading because all other components are almost full heigh - and you are unable to just "hover over"

**Comment by harshithmohan** [comment]
It's a firefox issue. It uses overlay scrollbars and hides thr scrollbar by default and there is no way for us to force it to be visible.

**Comment by bigretromike** [comment]
same thing is on mobile, also this is the default webui version that comes with installer 4.2.2

**Comment by ElementalCrisis** [comment]
Yeah nothing we can do about this, FF handles scrollbars much differently and requires the user to overwrite settings to fix it.

**Comment by bigretromike** [comment]
> Yeah nothing we can do about this, FF handles scrollbars much differently and requires the user to overwrite settings to fix it.

The issue is also on mobile 

And the second part of the issue is on Chrome on Win also - every other component have more space that its need it and this one is force to that height, which is a bit strange, cant this use flex or something or was this just force because of OCD ?

**Comment by ElementalCrisis** [comment]
IIRC, in v1, the panels have a minimum-height so they don't look really small. 

Not so much an issue in v2 though.

**Comment by bigretromike** [comment]
> IIRC, in v1, the panels have a minimum-height so they don't look really small.
> 
> Not so much an issue in v2 though.

can I somehow test v2 on stable ?

**Comment by ElementalCrisis** [comment]
No, its not compatible with the stable version. 

We're looking at releasing the next stable in about 4-6 weeks if everything goes smoothly.
